### ISSUE TITLE
Build instructions do not seem to work

### ISSUE THREAD

**Issue by cchulo** [Altaflux/gb-rp2350#3]
Was following your instructions for building it, and it seems like the rp2350 does not recognize the output binary as a uf2. When dragging and dropping the output gb-rp2350 the pico2 never reboots. This tells me something is wrong with the output gb-rp2350 file.
![image](https://github.com/user-attachments/assets/b9eb14bc-7009-4b8c-80b4-1a76cea16283)

Here is the [compile.log](https://github.com/user-attachments/files/18052235/compile.log)

The .env is pretty much .env.example renamed to .env, i already have the display as in your README:

```bash
ROM_LOCATION = "FLASH"
BOOT_ROM_PATH = "dmg_boot.bin"
DISPLAY_DRIVER="mipidsi::models::ILI9341Rgb565"
DISPLAY_WIDTH = 240
DISPLAY_HEIGHT = 320
GAMEBOY_RENDER_WIDTH = 320
GAMEBOY_RENDER_HEIGHT = 240
DISPLAY_ROTATION=90
DISPLAY_MIRRORED=true
DISPLAY_COLOR_INVERT = true
FRAME_RATE = 30
```

**Comment by cchulo** [comment]
one thing i thought of, are the build instructions for Windows only? I am on linux and am wondering if this is an issue. Will try the build instructions again when I am on a windows machine.

**Comment by cchulo** [comment]
i looked around and found that you need `picotool` to convert rust binaries into uf2:

`picotool uf2 convert /path/to/project/target/thumbv8m.main-none-eabihf/release/gb-rp2350 -t elf ./gb-rp2350.uf2`

https://murraytodd.medium.com/rust-with-the-raspberry-pi-pico-2-rp2350-e5f537af1c25

**Comment by Altaflux** [comment]
Hi @cchulo you are right, the instructions are unclear and wrong on how to upload the binary!
I will correct the instructions, thanks for noticing it,

**Comment by Altaflux** [comment]
Instructions have been updated.

**Comment by cchulo** [comment]
great thank you :) thanks for the hard work
